AWSTemplateFormatVersion: '2010-09-09'
Description: 'Creates backend resources including Lambda, IAM roles, and API Gateway.'

Resources:
  # This is the permission set (Role) that our Lambda function will use
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  # This is a placeholder for the list_files Lambda function
  ListFilesLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: list-files-function
      Runtime: python3.9
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn # Uses the role created above
      Code:
        ZipFile: |
          import json
          def handler(event, context):
              return {
                  'statusCode': 200,
                  'body': json.dumps('Hello from the list_files Lambda!')
              }

  # --- API Gateway Resources ---

  MyApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: FileStorageApi

  FilesResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref MyApiGateway
      ParentId: !GetAtt MyApiGateway.RootResourceId
      PathPart: files # This creates the /files path

  FilesGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref MyApiGateway
      ResourceId: !Ref FilesResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ListFilesLambdaFunction.Arn}/invocations"

  ApiGatewayLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ListFilesLambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${MyApiGateway}/*/*"

Outputs:
  LambdaFunctionName:
    Description: "Name of the ListFiles Lambda function"
    Value: !Ref ListFilesLambdaFunction
  ApiGatewayEndpoint:
    Description: "Endpoint URL for the API Gateway"
    Value: !Sub "https://${MyApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod" # Default stage is 'prod' unless specified